export const swapElements = (arr, index1, index2) => {
  console.log({ index1, index2 });
  let data = [...arr];
  [data[index1], data[index2]] = [data[index2], data[index1]];
  return data;
};
export const preDefinedTemplate = [
  {
    template: "Articles",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        key: "date",
        value: "",
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "div",
        type: "images",
        key: "images",
        value: "",
        placeholder: "Enter the Image URL",
        imgs: [
          {
            src: "",
            alt: "",
          },
        ],
        isRequired: true,
        isActive: true,
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ],
  },
  {
    template: "Careers",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        key: "date",
        value: "",
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "div",
        type: "images",
        key: "images",
        value: "",
        placeholder: "Enter the Image URL",
        imgs: [
          {
            src: "",
            alt: "",
          },
        ],
        isRequired: true,
        isActive: true,
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ],
    seo: {
      metaDescription: "",
      imagePreviewUrl: "",
      keywords: [],
      canonicalLink: "",
    },
  },
  {
    template: "Events & Tradeshows",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        key: "date",
        value: "",
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ],
    seo: {
      metaDescription: "",
      imagePreviewUrl: "",
      keywords: [],
      canonicalLink: "",
    },
  },
  {
    template: "FAQ",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        key: "date",
        value: "",
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ],
    seo: {
      metaDescription: "",
      imagePreviewUrl: "",
      keywords: [],
      canonicalLink: "",
    },
  },
  {
    template: "News",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        key: "date",
        value: "",
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "div",
        type: "images",
        key: "images",
        value: "",
        placeholder: "Enter the Image URL",
        imgs: [
          {
            src: "",
            alt: "",
          },
        ],
        isRequired: true,
        isActive: true,
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ],
    seo: {
      metaDescription: "",
      imagePreviewUrl: "",
      keywords: [],
      canonicalLink: "",
    },
  },
  {
    template: "Newsletters",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        key: "date",
        value: "",
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ],
    seo: {
      metaDescription: "",
      imagePreviewUrl: "",
      keywords: [],
      canonicalLink: "",
    },
  },
  {
    template: "Press Release",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        key: "date",
        value: "",
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ],
    seo: {
      metaDescription: "",
      imagePreviewUrl: "",
      keywords: [],
      canonicalLink: "",
    },
  },
  {
    template: "Podcasts",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        key: "date",
        value: "",
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "div",
        type: "images",
        key: "images",
        value: "",
        placeholder: "Enter the Image URL",
        imgs: [
          {
            src: "",
            alt: "",
          },
        ],
        isRequired: true,
        isActive: true,
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ],
    seo: {
      metaDescription: "",
      imagePreviewUrl: "",
      keywords: [],
      canonicalLink: "",
    },
  },
  {
    template: "Testimonials",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        key: "date",
        value: "",
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
      },
      {
        tag: "div",
        type: "images",
        key: "images",
        value: "",
        placeholder: "Enter the Image URL",
        imgs: [
          {
            src: "",
            alt: "",
          },
        ],
        isRequired: true,
        isActive: true,
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ],
    seo: {
      metaDescription: "",
      imagePreviewUrl: "",
      keywords: [],
      canonicalLink: "",
    },
  },
];
