export const swapElements = (arr, index1, index2) => {
  console.log({ index1, index2 });
  let data = [...arr];
  [data[index1], data[index2]] = [data[index2], data[index1]];
  return data;
};
export const preDefinedTemplate = [
  {
    template: "Articles",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Header",
        label: "Header",
        size: "lg",
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Title",
        size: "md",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Sub Title",
        size: "sm",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "md"
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "lg"
      },
      // {
      //   tag: "div",
      //   type: "images",
      //   key: "images",
      //   value: "",
      //   placeholder: "Enter the Image URL",
      //   imgs: [
      //     {
      //       src: "",
      //       alt: "",
      //     },
      //   ],
      //   isRequired: true,
      //   isActive: true,

      // },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        label: "Text Editor",
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ],
  },
  {
    template: "Careers",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Header",
        size: "lg",
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Title",
        size: "md",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Sub Title",
        size: "sm",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "md"
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "lg"
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        label: "",
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ]
  },
  {
    template: "Events & Tradeshows",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Header",
        size: "lg",
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Title",
        size: "md",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Sub Title",
        size: "sm",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "md"
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "lg"
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        label: "",
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ]
  },
  {
    template: "FAQ",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Header",
        size: "lg",
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Title",
        size: "md",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Sub Title",
        size: "sm",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "md"
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "lg"
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        label: "Text Editor",
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ]
  },
  {
    template: "News",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Header",
        size: "lg",
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Title",
        size: "md",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Sub Field",
        size: "sm",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "md"
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "lg"
      },
      {
        tag: "div",
        type: "images",
        key: "images",
        value: "",
        placeholder: "Enter the Image URL",
        imgs: [
          {
            src: "",
            alt: "",
          },
        ],
        isRequired: true,
        isActive: true,
        label: "",
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        label: "",
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ],
  },
  {
    template: "Newsletters",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Header",
        size: "lg",
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Title",
        size: "md",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Sub Title",
        size: "sm",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "md"
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "lg"
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        label: "html",
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ]
  },
  {
    template: "Press Release",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Header",
        size: "lg",
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Title",
        size: "md",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Sub Title",
        size: "sm",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "md"
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "lg"
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        label: "html",
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ]
  },
  {
    template: "Podcasts",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Header",
        size: "lg",
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Title",
        size: "md",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Sub Title",
        size: "sm",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "md"
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "lg"
      },
      {
        tag: "div",
        type: "images",
        key: "images",
        value: "",
        placeholder: "Enter the Image URL",
        imgs: [
          {
            src: "",
            alt: "",
          },
        ],
        isRequired: true,
        isActive: true,
        label: "",
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        label: "Text Editor",
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ]
  },
  {
    template: "Testimonials",
    components: [
      {
        tag: "input",
        type: "text",
        key: "header",
        value: "",
        description: "",
        placeholder: "Enter the Header data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Header",
        size: "lg",
      },
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Title",
        size: "md",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "input",
        type: "text",
        key: "subTitle",
        value: "",
        description: "",
        placeholder: "Enter the Sub-Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Sub Title",
        size: "sm",
      },
      {
        tag: "input",
        type: "date",
        key: "date",
        value: "",
        description: "",
        placeholder: "Enter the date",
        size: "sm",
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "md"
      },
      {
        tag: "textarea",
        type: "text",
        key: "description",
        value: "",
        description: "",
        placeholder: "Enter the Description data",
        min: 5,
        max: 300,
        isRequired: true,
        isActive: true,
        label: "Description",
        size: "lg"
      },
      {
        tag: "div",
        type: "images",
        key: "images",
        value: "",
        placeholder: "Enter the Image URL",
        imgs: [
          {
            src: "",
            alt: "",
          },
        ],
        isRequired: true,
        isActive: true,
        label: "",
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        label: "Text Editor",
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
      },
    ]
  },
  {
    template: "Videos",
    components: [
      {
        tag: "input",
        type: "text",
        key: "title",
        value: "",
        description: "",
        placeholder: "Enter the Title data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "Title",
        size: "lg"
      },
      {
        tag: "input",
        type: "text",
        key: "url",
        value: "",
        description: "",
        placeholder: "Enter the Video url data",
        min: 5,
        max: 100,
        isRequired: true,
        isActive: true,
        label: "URL",
        size: "lg"
      },
      {
        tag: "select",
        type: "text",
        key: "category",
        value: "",
        description: "",
        placeholder: "Select the Category",
        options: [
          { label: "3D", value: "3D" },
          { label: "Raspberry", value: "Raspberry" },
          { label: "Smart", value: "Smart" },
          { label: "MIPI", value: "MIPI" },
          { label: "Camera", value: "Camera" },
        ],
        isRequired: true,
        isActive: true,
        label: "Category",
      },
      {
        key: "htmlEditor",
        value: "",
        isRequired: true,
        isActive: true,
        label: "",
        placeholder: "Enter the HTML code here",
      },
      {
        key: "seo",
        metaDescription: "",
        imagePreviewUrl: "",
        keywords: [],
        canonicalLink: "",
        placeholder: "SEO",
        value: "",
      },
    ],
  },
];
