export let template = {
  name: "",
  description: "",
  settings: {
    seo: {
      title: "",
      metaDescription: "",
      imagePreviewUrl: "",
      keywords: [],
      canonicalLink: "",
    },
    language: [
      {
        languageKey: "",
        content: "",
      },
    ],
    versionManagement: {
      isActive: true,
    },
    stages: {
      isActive: true,
    },
  },
  dateTime: new Date(),
  header: {},
  footer: {},
  components: {
    Header: {
      tag: "input",
      type: "text",
      key: "header",
      value: "",
      description: "",
      placeholder: "Enter the Header data",
      min: 5,
      max: 100,
      isRequired: true,
      isActive: true,
      size: "lg",
    },
    Title: {
      tag: "input",
      type: "text",
      key: "title",
      value: "",
      description: "",
      placeholder: "Enter the Title data",
      min: 5,
      max: 100,
      isRequired: true,
      isActive: true,
      size: "lg",
    },
    SubTitle: {
      tag: "input",
      type: "text",
      key: "subTitle",
      value: "",
      description: "",
      placeholder: "Enter the Sub-Title data",
      min: 5,
      max: 100,
      isRequired: true,
      isActive: true,
    },
    Description: {
      tag: "textarea",
      type: "text",
      key: "description",
      value: "",
      description: "",
      placeholder: "Enter the Description data",
      min: 5,
      max: 300,
      isRequired: true,
      isActive: true,
    },
    Images: {
      tag: "div",
      type: "images",
      key: "images",
      value: "",
      placeholder: "Enter the Image URL",
      imgs: [
        {
          src: "",
          alt: "",
        },
      ],
      isRequired: true,
      isActive: true,
    },
    // Links: {
    //   key: "links",
    //   text: {
    //     tag: "input",
    //     type: "text",
    //     key: "urlText",
    //     value: "",
    //     description: "",
    //     placeholder: "",
    //     min: 3,
    //     max: 150,
    //   },
    //   link: {
    //     tag: "input",
    //     type: "text",
    //     key: "urlLink",
    //     value: "",
    //     description: "",
    //     placeholder: "",
    //   },
    //   description: "",
    //   isRequired: true,
    //   isActive: true,
    // },
    Cards: {
      tag: "div",
      type: "object",
      key: "cards",
      components: {
        title: {
          tag: "input",
          type: "text",
          key: "title",
          value: "",
          description: "",
          placeholder: "",
          min: 5,
          max: 100,
          isRequired: true,
          isActive: true,
        },
        description: {
          tag: "textarea",
          type: "text",
          key: "description",
          value: "",
          description: "",
          placeholder: "",
          min: 5,
          max: 300,
          isRequired: true,
          isActive: true,
        },
        img: {
          tag: "input",
          type: "text",
          key: "imgUrl",
          value: "",
          description: "",
          placeholder: "",
          isRequired: true,
          isActive: true,
        },
        url: {
          text: {
            tag: "input",
            type: "text",
            key: "urlText",
            value: "",
            description: "",
            placeholder: "",
            min: 3,
            max: 50,
            isRequired: true,
            isActive: true,
          },
          link: {
            tag: "input",
            type: "text",
            key: "urlLink",
            value: "",
            description: "",
            placeholder: "",
            isRequired: true,
            isActive: true,
          },
          description: "",
          isRequired: true,
          isActive: true,
        },
      },
      isRequired: true,
      isActive: true,
    },
    List: {
      tag: "div",
      type: "object",
      key: "list",
      lists: [
        {
          tag: "input",
          type: "text",
          key: "listText",
          value: "",
          description: "",
          placeholder: "Enter the list data",
          min: 5,
          max: 100,
        },
      ],
      isRequired: true,
      isActive: true,
    },
    Html: {
      key: "htmlEditor",
      value: "",
      isRequired: true,
      isActive: true,
      placeholder: "Enter the HTML code here",
    },
    Button: [
      {
        tag: "button",
        type: "button",
        key: "button",
        value: "",
        description: "",
        isRequired: true,
        isActive: true,
      },
    ],
    Date: {
      key: "date",
      value: "",
      isRequired: true,
      isActive: true,
    },
  },
};
